---
banner: img/blog/sc2.png
title: Free Python Workshop
author: Juan Cortes
date: '2024-08-10'
slug: workshop
categories: [workshop]
tags: []
---

We’re excited to be hosting a Software Carpentry workshop and hope you are too. Our upcoming workshop will be on **August 19th - 21st, 2024, from 9am - 1pm**. A few notes:


* Software Carpentry aims to help researchers get their work done in less time and with less pain by teaching them basic research computing skills. This hands-on workshop will cover basic concepts and tools, including program design, version control, data management, and task automation. Participants will be encouraged to help one another and to apply what they have learned to their own research problems.

* This is a free online event, open to all faculty, staff and students at any CSU campus. Checkout the workshop website for more info: [Plotting and Programming in Python](https://project-da-fanh.github.io/2024-08-19-CSU-online/)

* Regardless of how you choose to install it, please make sure you install Python version 3.x (e.g., 3.6 is fine). There are setup instructions on the workshop website. We will teach Python using the Jupyter Notebook, a programming environment that runs in a web browser (Jupyter Notebook will be installed by Anaconda). Someone will be there by 8:30 (Mon) to help with installation issues and answer general questions.

Note: You don't need to have any previous knowledge of the tools that will be presented at the workshop.

**[Register Here!](https://forms.gle/ZQ3KPq2UBxxvPH9YA)**



Let us know if you have any questions, please contact fanh.analytics@gmail.com. Otherwise, we will see you Monday morning!

Looking forward to seeing you soon!

----