---
banner: img/blog/r.png
title: R for Reproducible Scientific Analysis
author: Juan Cortes
date: '2024-12-03'
slug: workshop
categories: [workshop]
tags: []
---

We’re excited to be hosting a Software Carpentry workshop and hope you are too. Our upcoming workshop will be on **January 13-15, 2025, from 9:00am-1:00pm PST**. A few notes:


* Software Carpentry aims to help researchers get their work done in less time and with less pain by teaching them basic research computing skills. This hands-on workshop will cover basic concepts and tools, including program design, version control, data management, and task automation. Participants will be encouraged to help one another and to apply what they have learned to their own research problems.

* This is a hybrid event, open to all faculty, staff and students at any CSU campus. It will take place via Zoom and in-person at CSU, Chico. Registration fees are \$25, or \$10 for students. Space is limited; please contact the organizers to be placed on a hold list if needed. Checkout the workshop website for more info: [R for Reproducible Scientific Analysis](https://project-da-fanh.github.io/2025-01-13-CSU-online/)

* Please make sure you install R Studio before the workshop. R is a programming language that is especially powerful for data exploration, visualization, and statistical analysis. To interact with R, we use RStudio. Someone will be there by 8:30 (Mon) to help with installation issues and answer general questions.

Note: You don't need to have any previous knowledge of the tools that will be presented at the workshop.

**[Register Here!](https://www.eventbrite.com/e/r-for-reproducible-scientific-analysis-3-half-days-registration-1084774713369?aff=oddtdtcreator)**



Let us know if you have any questions, please contact fanh.analytics@gmail.com. Otherwise, we will see you Monday morning!

Looking forward to seeing you soon!

----