baseurl = "https://project-dafanh.netlify.app/" 
title = "Grow your Future with us"
theme = "hugo-universal-theme"
languageCode = "en-us"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

# number of words of summarized post content (default 70)
summaryLength = 50

# Define the number of posts per page
paginate = 10

[menu]


##  -----Main menu------ ###
[[menu.main]]
    name       = "Home"
    identifier = "menu.home"
    url        = "/"
    weight     = 1

## ----BLOG ---- ###
[[menu.main]]
    name       = "News"
    identifier = "menu.news"
    url        = "/blog/"
    weight     = 2

    
## ----WORKSHOPS ---- ###
[[menu.main]]
    name       = "Data Skills Workshops"
    url        = "/workshop/"
    weight     = 3

## ---- STUDENTS ---- ###
[[menu.main]]
    name       = "For Current Students"
    identifier = "menu.students"
    url        = ""
    weight     = 4


[[menu.main]]
    name       = "AMA Career Conversations"
    url        = "/careers/"
    weight     = 1
    parent     = "menu.students"


[[menu.main]]
    name       = "Applied Research Internship"
    url        = "/internship"
    weight     = 3
    parent     = "menu.students"

[[menu.main]]
    name       = "Fellowship"
    url        = "/fellowship"
    weight     = 4
    parent     = "menu.students"


#[[menu.main]]
#    name       = "Option 1: Default Page"
#    url        = "/"
#    weight     = 1
#    parent     = "menu.home"


## ----FEATURES ---- ###
#[[menu.main]] # In nav bar
#    name       = "Features"
#    identifier = "menu.features"
#    url        = "/img/template-easy-customize.png"
#    weight     = 3

#[[menu.main]] # bold left column in drop down
#    name       = "Shortcodes"
#    identifier = "section.shortcodes"
#    url        = ""
#    weight     = 1
#    parent     = "menu.features"
#   post       = 1
 
#[[menu.main]]  # bold right column in drop down
#    name       = "Header variations"
#    identifier = "section.headervariations"
#    url        = ""
#    weight     = 2
#    parent     = "menu.features"
#    post       = 2

#[[menu.main]] # first item in left side list
#    name       = "Accordions"
#    url        = ""
#    weight     = 1
#    parent     = "section.shortcodes"

#[[menu.main]]
#    name       = "Alerts"
#    url        = ""
#    weight     = 2
#    parent     = "section.shortcodes"

#[[menu.main]]
#    name       = "Buttons"
#    url        = ""
#    weight     = 3
#    parent     = "section.shortcodes"

#[[menu.main]]
#    name       = "Content Boxes"
#    url        = ""
#    weight     = 4
#   parent     = "section.shortcodes"

#[[menu.main]]
#    name       = "Horizontal Blocks"
#    url        = ""
#    weight     = 5
#    parent     = "section.shortcodes"

#[[menu.main]] # first item in right side list
#    name       = "Default Sticky Header"
#    url        = ""
#    weight     = 1
#    parent     = "section.headervariations"

#[[menu.main]]
#    name       = "No Sticky Header"
#    url        = ""
#    weight     = 2
#    parent     = "section.headervariations"

#[[menu.main]]
#    name       = "Light Header"
#    url        = ""
#    weight     = 3
#    parent     = "section.headervariations"

## ----ACTIVITIES ---- ###
#[[menu.main]]
#    name       = "Activities"
#    identifier = "menu.activities"
#    url        = ""

###--- Column 1 ---###
#[[menu.main]]
#    name       = "Project Areas"
#    identifier = "section.goals"
#    url        = ""
#    weight     = 1
#    parent     = "menu.activities"
#    post       = 1

#[[menu.main]]
#    name       = "Career Connection"
#    url        = ""
#    weight     = 1
#    parent     = "section.goals"
    
#[[menu.main]]
#    name       = "Faculty Development"
#    url        = ""
#    weight     = 2
#    parent     = "section.goals"

#[[menu.main]]
#    name       = "Student Internship"
#    url        = ""
#    weight     = 3
#    parent     = "section.goals"
    
#[[menu.main]]
#    name       = "Community Development"
#    url        = ""
#    weight     = 4
#    parent     = "section.goals"
    
###--- Column 2 ---###

#[[menu.main]]
#    name       = "Upcoming Events"
#    identifier = "section.events"
#    url        = ""
#    weight     = 2
#    parent     = "menu.activities"
#    post       = 2
    
#[[menu.main]]
#    name       = "Events"
#    url        = "/events"
#   weight     = 1
#    parent     = "section.events"

###--- Column 3 ---###
#[[menu.main]]
#    name       = "Campus Resources"
#    identifier = "section.resources"
#    url        = ""
#    weight     = 2
#    parent     = "menu.activities"
#    post       = 3

#[[menu.main]]
#    name       = "Chico"
#    url        = ""
#    weight     = 1
#    parent     = "section.resources"

#[[menu.main]]
#    name       = "San Bernardino"
#    url        = ""
#    weight     = 2
#    parent     = "section.resources"

#[[menu.main]]
#    name       = "Packages"
#    url        = ""
#    weight     = 1
#    parent     = "section.marketing"



## ---- ABOUT ---- ###
[[menu.main]]
    name       = "About"
    identifier = "menu.about"
    url        = ""
    weight     = 6
    
[[menu.main]]
    name       = "About Us"
    url        = "/about/"
    weight     = 1
    parent     = "menu.about"

[[menu.main]]
    name       = "Timeline of Activities"
    url        = "/timeline/"
    weight     = 2
    parent     = "menu.about"
    
[[menu.main]]
    name       = "Our Team"
    url        = "/team/"
    weight     = 3
    parent     = "menu.about"

#[[menu.main]]
#    identifier = "contact"
#    name       = "Contact"
#    url        = "/contact/"
#    weight     = 7


# Top bar social links menu
    
[[menu.topbar]]
    weight = 1
    name = "YouTube"
    url = "https://www.youtube.com/@calstate_dafanh"
    pre = "<i class='fab fa-2x fa-youtube'></i>"
    
[[menu.topbar]]
    weight = 2
    name = "Twitter"
    url = "http://twitter.com/calstate_dafanh"
    pre = "<i class='fab fa-2x fa-twitter'></i>"

[[menu.topbar]]
    weight = 3
    name = "Instagram"
    url = "http://instagram.com/calstate_dafanh/"
    pre = "<i class='fab fa-2x fa-instagram'></i>"

[[menu.topbar]]
    weight = 4
    name = "Email"
    url = "mailto:fanh.analytics@gmail.com"
    pre = "<i class='fas fa-2x fa-envelope'></i>"

[params]
    viewMorePostLink = "/blog/"
    author = "Project Directors"
    defaultKeywords = [""]
    mainSections = ["blog"]
    defaultDescription = "Template Description"

    # Social media
    facebook_site = "" # the Facebook handle of your site ('https://www.facebook.com/HANDLE')
    twitter_site = "GoHugoIO" # the Twitter handle of your site (without the '@')
    default_sharing_image = "img/sharing-default.png"

    # Google Maps widget: If `googleMapsApiKey` is not set, no key will be passed to Google (which likely results in a broken map widget).
    enableGoogleMaps = false
    googleMapsApiKey = "AIzaSyAv7Sza8NSp9_l_g8G2vlo0H4ydEPn_2jY"

    latitude = "-12.043333"
    longitude = "-77.028333"

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "blue"
    custom_css  = ["css/custom.css"]
    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 50 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - register your account to https://formspree.io/register
    # - login and create new form
    # - set your form's endpoint url under 'formspree_action' below
    # - upload the generated site to your server
    # - test a dummy email yourself
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io endpoint url
    formspree_action = "https://formspree.io/sample/of/endpoint"
    contact_form_ajax = false

    # Formspree form supports Google reCAPTCHA Key (type v2).
    # If you use this feature, you should enable reCAPTCHA feature in the Formspree dashboard.
    #
    # By default, Formspree use a redirect page for recaptcha widget.
    # If you use a recaptcha widget in your contact page, you should do next steps.
    # (if you don't want, skip these steps)
    #
    #   1. register your site on Google recaptcha admin page: https://www.google.com/recaptcha/admin
    #   2. select reCAPTCHA v2 and checkbox widget type.
    #   3. remember site key and secret key.
    #   4. enter secret key into "Custom reCAPTCHA Key" field in your Formspree form setting page.
    #   5. change `enableRecaptchaInContactForm` is to true
    #   6. enter site key into `googleRecaptchaKey` to enable a recaptcha widget in your page.
    #
    enableRecaptchaInContactForm = false
    googleRecaptchaKey = "site_key_for_google_recaptcha"

    about_us = "<p>Enriching education at the intersection of Data Analytics and the Food, Agriculture, Natural and Human Sciences through professional experiential learning and curriculum development. </p>"
    copyright = " Project DA-FANH is a result of grant no. 2021-77040-34880 from the USDA National Institute of Food and Agriculture. Copyright (c) 2022, Project DA-FANH; all rights reserved."

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    disabled_logo = false
    logo_text = "Project DA-FANH"
    logo = "img/DA-FANH-Logo-1-bw.png"
    logo_small = "img/DA-FANH-Logo-1-bw.png"
    contact_url = "/contact"
    Address = """<p class="text-uppercase"><strong>Email</strong>
    <br>fanh.analytics@gmail.com<br>"""
    
    # Address = """<p class="text-uppercase"><strong>Email</strong>
    #    <br>13/25 New Avenue
    #    <br>Newtown upon River
    #    <br>45Y 73J
    #    <br>England
    #    <br>
    #    <strong>Great Britain</strong>
    #  </p>
    #  """

[permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

# Enable or disable top bar with social icons
[params.topbar]
    enable = true
    text = """<p class="hidden-sm hidden-xs">Contact us at fanh.analytics@gmail.com.</p>
      <p class="hidden-md hidden-lg">
      <a href="mailto:fanh.analytics@gmail.com" data-animate-hover="pulse"><i class="fas fa-envelope"></i></a>
      </p>
      """

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true

[params.carouselCustomers]
    items = 4
    auto_play = false
    slide_speed = 500
    pagination_speed = 500

[params.carouselTestimonials]
    items = 4
    auto_play = false
    slide_speed = 2000
    pagination_speed = 1000

[params.carouselHomepage]
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more information take a look at the README.
    enable = true
    auto_play = true
    slide_speed = 2000
    pagination_speed = 1000


[params.see_more]
    enable = false
    icon = "far fa-file-alt"
    title = "Do you want to see more?"
    subtitle = "We have prepared for you more than 40 different HTML pages, including 5 variations of homepage."
    link_url = "#"
    link_text = "Check other homepages"


[params.features]
    enable = true
    cols = 3 # Default: 3, Available values 2,3,4,6
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more information take a look at the README.

[params.testimonials]
    enable = false
    # All testimonials are defined in their own files. You can find example items
    # at 'exampleSite/data/testimonials'.
    # For more information take a look at the README.
    title = "Testimonials"
    subtitle = "Hear what people have to say "

[params.whatisfanh]
    enable = true
    title = "What are the FANH Sciences?"
    subtitle = "The term “food, agriculture, natural resources and human sciences” (FANH sciences) includes activities in food and fiber, agricultural, renewable energy and natural resources, forestry, and physical and social sciences, or rural economic, community, or business development including activities relating to the following:"
    subtitle2 = "What careers exist in FANH? The USDA HSI Education Grants Program lists the occupations below as examples of “mission critical” occupations that the USDA is looking to recruit talented students from Hispanic Serving Institutions into:"
    
[params.clients]
    enable = true
    # All clients are defined in their own files. You can find example items
    # at 'exampleSite/data/clients'.
    title = "Our Partners"
    subtitle = "We could not accomplish great things without the support and collaboration with these organizations."

[params.recent_posts]
    enable = true
    title = "News and Events"
    subtitle = ""
    hide_summary = false

[params.footer.recent_posts]
    enable = true

[taxonomies]
  category = "categories"
  tag = "tags"
  author = "authors"
